# MegaLinter configuration file
# More info at https://megalinter.io/latest/config-file/

# Configuration
APPLY_FIXES: none # Read-only mode: do not rewrite repository files
SHOW_ELAPSED_TIME: true

# Limit MegaLinter to file types that exist in this repository.
ENABLE:
  - REPOSITORY
  - PYTHON
  - JAVASCRIPT
  - TYPESCRIPT
  - TSX
  - CSS
  - HTML
  - SQL
  - YAML
  - JSON
  - MARKDOWN
  - ENV
  - POWERSHELL

# Exclusions
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - client/node_modules
  - client/dist
  - node_modules
  - .venv
  - dist
  - build
  - __pycache__
  - .pytest_cache
  - .ruff_cache
  - coverage
  - raw_data
  - megalinter-reports
  - Scripts results

FILTER_REGEX_EXCLUDE: "(^|/)(git_status_output\\.txt|pytest_output\\.txt|ruff_output\\.txt|test_failures\\.log|tests_output\\.txt|tests_output2\\.txt|2ms-report[^/]*\\.json)$"

# Avoid secret-scanner noise from generated local benchmark reports.
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-path 2ms-report.json --skip-path 2ms-report-filtered.json --skip-path megalinter-reports"

# Flavors
# FLAVOR_SUGGESTION: python, javascript

# Languages and Linters
# By default, MegaLinter enables all linters for all languages found in the repository
# You can disable some if they are too noisy
# DISABLE:
#   - REPOSITORY_GIT_DIFF
#   - SPELL_CSPELL # Can be very noisy

# Configuration for specific linters
# BASH_SHELLCHECK_ARGUMENTS: "--severity=warning"
