# MegaLinter configuration file
# More info at https://megalinter.io/latest/config-file/

# Configuration
APPLY_FIXES: all # Apply fixes automatically (for local or CI that allows pushing)
SHOW_ELAPSED_TIME: true
FILE_IO_THREADS: 4

# Restrict MegaLinter to descriptors used by this repository
ENABLE: PYTHON,JAVASCRIPT,TYPESCRIPT,TSX,CSS,HTML,SQL,YAML,JSON,ENV,POWERSHELL,REPOSITORY

# Keep Ruff/ESLint checks in tests.yml and let MegaLinter focus on other linters
DISABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES

# Exclusions
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - node_modules
  - .venv
  - dist
  - build
  - __pycache__
  - .pytest_cache
  - .ruff_cache
  - coverage
  - raw_data
  - Scripts results

FILTER_REGEX_EXCLUDE: "(^|/)(git_status_output\\.txt|pytest_output\\.txt|ruff_output\\.txt|test_failures\\.log|tests_output\\.txt|tests_output2\\.txt)$"

# Flavors
# FLAVOR_SUGGESTION: python, javascript

# Languages and Linters
# By default, MegaLinter enables all linters for all languages found in the repository
# You can disable some if they are too noisy
# DISABLE:
#   - REPOSITORY_GIT_DIFF
#   - SPELL_CSPELL # Can be very noisy

# Configuration for specific linters
# BASH_SHELLCHECK_ARGUMENTS: "--severity=warning"
