sonar.python.version=3.13
sonar.issue.ignore.multicriteria=commentFixtureJavascriptUrl
sonar.issue.ignore.multicriteria.commentFixtureJavascriptUrl.ruleKey=typescript:S1523
sonar.issue.ignore.multicriteria.commentFixtureJavascriptUrl.resourceKey=client/tests/unit/*Comment*.test.tsx
